### ISSUE TITLE
Rails run on UbuntuLTS18.04 error

### ISSUE THREAD

**Issue by tqf6** [Websoft9/ansible-ruby#4]
## Language

- [ ] Chinese
- [ ] English

## Content error

![image](https://user-images.githubusercontent.com/83911329/123240102-97552780-d512-11eb-85b9-98e5a4d0903d.png)
![image](https://user-images.githubusercontent.com/83911329/123240246-b94eaa00-d512-11eb-9321-dbf6c337fc21.png)

## Content optimization

Provide us with content optimization, e.g easy to read, simplify the steps, step by step, precise expression.

* URL: 
* Description: 

## New content

Describe important content what do you think is important in this documentation.

**What content do you want to add?**  

(describe here) 

**Steps for the content**  

4. Modify file '....'

**Comment by qiaofeng1227** [comment]
```
root@ip-172-31-46-32:/data/apps/rails/myrails# systemctl status rails
● rails.service - Rails Service
   Loaded: loaded (/lib/systemd/system/rails.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2021-06-24 10:19:56 UTC; 12s ago
  Process: 4629 ExecStart=/usr/bin/bash -lc rails s -p 3000 -b 0.0.0.0 (code=exited, status=203/EXEC)
 Main PID: 4629 (code=exited, status=203/EXEC)
root@ip-172-31-46-32:/data/apps/rails/myrails# 
```

**Comment by qiaofeng1227** [comment]
```
ubuntu@ip-172-31-46-32:/data/apps/rails/myrails$ rails s -p 3000 -b 0.0.0.0
=> Booting Puma
=> Rails 6.1.3.2 application starting in development 
=> Run `bin/rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	38: from bin/rails:2:in `<main>'
	37: from bin/rails:2:in `load'
	36: from /data/apps/rails/myrails/bin/spring:7:in `<top (required)>'
	35: from /data/apps/rails/myrails/bin/spring:7:in `tap'
	34: from /data/apps/rails/myrails/bin/spring:10:in `block in <top (required)>'
	33: from /data/apps/rails/myrails/bin/spring:10:in `require'
	32: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
	31: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
	30: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
	29: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
	28: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
	27: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
	26: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
	25: from /data/apps/rails/myrails/bin/rails:5:in `<top (required)>'
	24: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	23: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	22: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	21: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	20: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	19: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands.rb:18:in `<main>'
	18: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/command.rb:50:in `invoke'
	17: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/command/base.rb:69:in `perform'
	16: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	15: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	14: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	13: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/server/server_command.rb:135:in `perform'
	12: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/server/server_command.rb:135:in `tap'
	11: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	10: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/server/server_command.rb:35:in `start'
	 9: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/server/server_command.rb:71:in `create_tmp_directories'
	 8: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/server/server_command.rb:71:in `each'
	 7: from /data/apps/rails/myrails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/server/server_command.rb:72:in `block in create_tmp_directories'
	 6: from /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
	 5: from /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `each'
	 4: from /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
	 3: from /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
	 2: from /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
	 1: from /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /data/apps/rails/myrails/tmp/sockets (Errno::EACCES)
ubuntu@ip-172-31-46-32:/data/apps/rails/myrails$ ruby -v
```

**Comment by chendelin1982** [comment]
use ruby docker to replace it
